### ISSUE TITLE
Support for Angular V4

### ISSUE THREAD

**Issue by asaph26** [DanielYKPan/ng2-fan-menu#1]
Will this be upgraded to support AngularV4?

**Comment by DanielYKPan** [comment]
@asaph26 
Not yet. But I will upgrade it to V$ in this weekend.

**Comment by robinmaple** [comment]
Has this been upgraded to V4 yet? Thanks.

**Comment by robinmaple** [comment]
@DanielYKPan, any updates on this? You've made it all the way to Angular 2, it's a pity that people can't use it in Angular 4. Hopefully you'll have time to do it soon. Keep up the great work!

**Comment by DanielYKPan** [comment]
@robinmaple 
I kind of busy with other projects recently. I would update it as soon as possible.

**Comment by robinmaple** [comment]
Thanks a lot, buddy! Looking forward to it.

**Comment by bohyunbartowski** [comment]
@DanielYKPan when it will be upgraded to support Angular V4?

**Comment by DanielYKPan** [comment]
It has been updated to angular 4.

Thanks, guys
