### ISSUE TITLE
Animation query error

### ISSUE THREAD

**Issue by Relirk** [DanielYKPan/ng2-fan-menu#6]
When i import this library in to my app module.
It shows the following error in console.

      `animations_1.query` is not a function`

I'm using Angular 4.1.3, Angular Cli 4.1.3, Ionic 3.12.1, and Typescript 2.3.4

**Comment by DanielYKPan** [comment]
@Relirk 
animation query was introduced from angular version ^4.2.*
So you may consider to update you angular version
